### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by sdeleuze**
Hey, I have made various improvements, could you please merge them?

The last commit switch back to Spring MVC because JPA is a blocking API and should not be used as it is with WebFlux, that would lead to big scalability issues and should not be shown especially in such "official" example. But using WebFlux in tests is fine and recommended.

### CODE REVIEW

**Comment by arey** [comment]
Thanks a lot Sébastien for this PR and your recommandation to not use WebFlux with JPA. I've migrated to WebFlux in order to use the Kotlin routing DSL. 

Do you have any idea to fix the 2 tests that are ignored into the OwnerControllerTest class?

**Comment by sdeleuze** [comment]
Thanks for the quick merge. Any chance you could drop a note on http://javaetmoi.com/2017/12/migration-spring-web-mvc-vers-spring-webflux/ that in production, WebFlux server and JPA are not a good fit (client is perfectly ok)?

**Comment by sdeleuze** [comment]
Yeah sadly Kotlin routing DSL and JPA are not a good fit for now. We are experimenting on some Reactive/Async SQL support but nothing usable in production for now. I am not sure about migrating this sample since a JPA example is actually super useful. But why not creating a new fork maybe?

I think I forgot to change `@WebFluxTest` to `@WebMvcTest`, could you please change this?

Could you please detail what you are trying to achieve with the client ("How to submit data into a GET with the Webflux client"), I am not sure to understand?

**Comment by arey** [comment]
Hi @sdeleuze. I've added a post-scriptum to my blog entry and I've fixed the 2 unit tests.

I tried to change ```@WebFluxTest``` to ```@WebMvcTest``` but the build failed: https://travis-ci.org/spring-petclinic/spring-petclinic-kotlin/builds/341988016?utm_source=email&utm_medium=notification
The ```org.springframework.test.web.reactive.server.WebTestClient``` seems to not be injected. Any idea?

**Comment by sdeleuze** [comment]
@arey Sorry back from long vacations. Did you manage to find the error?

**Comment by arey** [comment]
No, I don't find it.

**Comment by sdeleuze** [comment]
I guess it is related to https://github.com/spring-projects/spring-boot/issues/12318.

**Comment by snicoll** [comment]
No it's not. Mocking with WebTestClient doesn't work with WebMvc (if that's what you're trying to do)

**Comment by arey** [comment]
Yes, we would like to use WebTestClient with WebMvc. @snicoll Do you know if it is plan?
@sdeleuze maybe we should rollback WebFlux usage?

**Comment by sdeleuze** [comment]
Since `WebTestClient` mocking is not available with WebMvc as said by @snicoll, what about migrating `*Controller` tests from `@WebFluxTest` to integration tests with `@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)` + `@AutoConfigureWebTestClient` like in [this test](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-test-autoconfigure/src/test/java/org/springframework/boot/test/autoconfigure/web/reactive/webclient/WebTestClientSpringBootTestIntegrationTests.java)?

**Comment by arey** [comment]
When it's possible, I prefer unit tests than integration tests. Thus returning to ```@WebMvcTest``` + ```MockMvc``` has my preference, even it we don't use WebFlux anymore :-(

**Comment by snicoll** [comment]
I agree with @arey. IMO going to full integration tests route only to be able to use `WebTestClient` is not warranted.

**Comment by sdeleuze** [comment]
Works for me.

**Comment by arey** [comment]
Thank you Sébastien and Stéphane for your analyse

**Comment by sdeleuze** [comment]
You're welcome, see also https://github.com/spring-guides/tut-spring-boot-kotlin for an example of a Kotlin + JPA idiomatic application.

**Comment by arey** [comment]
It's a really complete guide.  Thanks.
I've just applied the ```org.springframework.ui.set``` extension function.

**Pull request merged**
